name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'

      - name: Package
        run: |
          python setup.py sdist

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}