name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'

      - name: Package
        run: |
          python setup.py sdist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}